export const LOAD_MESSAGE_START = 'LOAD_MESSAGE_START';
export const LOAD_MESSAGE_SUCCESS = 'LOAD_MESSAGE_SUCCESS';
export const LOAD_MESSAGE_ERROR = 'LOAD_MESSAGE_ERROR';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
